---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install multiple packages
    package: 
      name: 
        - htop
        - tmux
        - neofetch

  - name: copy wallpaper file
    copy: 
      src: files/w.jpg
      dest: /usr/share/backgrounds/w.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: max
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr//share/backgrounds/w.jpg'"

  - name: set wallpaper position
    become_user: max
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
